# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.define "master1" do |master1|
		master1.vm.network "private_network", ip: "192.168.33.10"
		master1.vm.provider :virtualbox do |vb|
			vb.memory="512"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	config.vm.define "worker1" do |worker1|
		worker1.vm.network "private_network", ip: "192.168.33.11"
		worker1.vm.provider :virtualbox do |vb|
			vb.memory="512"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end 
	config.vm.define "worker2" do |worker2|
		worker2.vm.network "private_network", ip: "192.168.33.12"
		worker2.vm.provider :virtualbox do |vb|
			vb.memory="512"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	config.vm.define "worker3" do |worker1|
		worker1.vm.network "private_network", ip: "192.168.33.13"
		worker1.vm.provider :virtualbox do |vb|
			vb.memory="512"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end 

	config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
	echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
	sudo apt-get update
	sudo apt-get install -y docker-engine
	sudo usermod -aG docker $(whoami)
	SHELL

end
